# Generated by Django 3.0.3 on 2020-04-18 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stack', models.CharField(max_length=222)),
                ('university_attended', models.CharField(max_length=122)),
                ('started_uni', models.IntegerField()),
                ('ended_uni', models.IntegerField()),
                ('first_language', models.CharField(max_length=122)),
                ('started_first_lang', models.IntegerField()),
                ('ended_first_lang', models.IntegerField()),
                ('first_lang_source', models.CharField(max_length=122)),
                ('second_language', models.CharField(blank=True, max_length=122)),
                ('started_second_lang', models.IntegerField(blank=True)),
                ('ended_second_lang', models.IntegerField(blank=True)),
                ('second_lang_source', models.CharField(blank=True, max_length=122)),
                ('third_language', models.CharField(blank=True, max_length=122)),
                ('started_third_lang', models.IntegerField(blank=True)),
                ('ended_third_lang', models.IntegerField(blank=True)),
                ('third_lang_source', models.CharField(blank=True, max_length=122)),
                ('fourth_language', models.CharField(blank=True, max_length=122)),
                ('started_fourth_lang', models.IntegerField(blank=True)),
                ('ended_fourth_lang', models.IntegerField(blank=True)),
                ('fourth_lang_source', models.CharField(blank=True, max_length=122)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('age', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('About_me', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
