# Generated by Django 3.0.3 on 2020-04-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20200419_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='ended_fourth_lang',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='fourth_lang_source',
            field=models.CharField(blank=True, max_length=122, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='fourth_language',
            field=models.CharField(blank=True, max_length=122, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='started_fourth_lang',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
