# Generated by Django 3.0.3 on 2020-05-20 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_remove_userprofile_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='users-pix/'),
        ),
    ]
