# Generated by Django 3.0.3 on 2020-05-20 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_userprofile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='About_me',
            new_name='about',
        ),
    ]
