# Generated by Django 3.0.6 on 2020-06-03 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_userprofile_stack'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resume',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resume/'),
        ),
    ]
