# Generated by Django 3.0.6 on 2020-06-05 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_auto_20200605_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_superuser',
        ),
    ]
