# Generated by Django 3.0.6 on 2020-07-09 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0019_auto_20200605_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
    ]
