# Generated by Django 3.0.6 on 2020-07-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_remove_userprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='kolikay@yahoo.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
